apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeflux-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: kubeflux
      plugins:
        queueSort:
          enabled:
          - name: Coscheduling
          disabled:
          - name: '*'
        score:
          disabled:
          - name: '*'
        preFilter:
          enabled:
          - name: KubeFlux
        filter:
          enabled:
          - name: KubeFlux
