apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeflux-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
      apiVersion: kubescheduler.config.k8s.io/v1beta2
      kind: KubeSchedulerConfiguration
      leaderElection:
        leaderElect: false
      clientConnection:
        kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
      profiles:
      - schedulerName: kubeflux
        plugins:
          score:
            disabled:
            - name: '*'
          preFilter:
            enabled:
            - name: kubeflux
          filter:
            enabled:
            - name: kubeflux